import type { Metadata } from "next";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const raleway = Raleway({
	subsets: ["latin"], // add other subsets if needed
	weight: ["400", "500", "700"], // add required font weights
	display: "swap",
});

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["400", "500", "700"], // regular, medium, bold
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="bg-white dark:bg-neutral-800 transition-colors"
		>
			<body className={` ${montserrat.className} `}>
				<Header />
				{children}
			</body>
		</html>
	);
}
